version: "2.3"

services:
  # ROS Melodic master
  my-ros-master:
    image: ros:melodic-ros-core
    restart: on-failure
    tty: true 
    environment:
      - "ROS_IP=192.168.1.178"
      - "ROS_MASTER_URI=http://192.168.1.178:11311/"    
    # ports:
    #   - 11311:11311
    network_mode: "host"
    command: stdbuf -o L roscore


  # # ROS Melodic rosbot hardware layer
  # rosbot:
  #   image: husarion/rosbot:latest
  #   tty: true      
  #   restart: on-failure
  #   environment:
  #     - "ROS_IP=rosbot"
  #     - "ROS_MASTER_URI=http://192.168.1.178:11311"
  #     - "SERIAL_PORT=/dev/ttyS4" # default: ttyS1 - rosbot2.0; ttyS4 - rosbot2.0 `pro
  #   devices:
  #     - "/dev/ttyS4"   # must match environment SERIAL_PORT 
  #   command: roslaunch rosbot_description rosbot_docker.launch


  # ROS Melodic Rplidar
  rplidar:
    image: husarion/rplidar:latest
    tty: true      
    restart: unless-stopped
    environment: 
     - "ROS_IP=192.168.1.178"
     - "ROS_MASTER_URI=http://192.168.1.178:11311/"
    devices:
      - /dev/ttyUSB0
    network_mode: "host"
    command: roslaunch rplidar_ros rplidar.launch # For Rosbot 2.0 PRO use roslaunch rplidar_ros rplidar_a3.launch